# Generated by Django 5.0.7 on 2024-07-22 20:13

import Driver_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar', models.CharField(max_length=15, unique=True)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(max_length=15)),
                ('rc_img', models.ImageField(max_length=250, upload_to=Driver_app.models.truncate_filename)),
                ('license', models.ImageField(max_length=250, upload_to=Driver_app.models.truncate_filename)),
                ('insurance', models.ImageField(max_length=250, upload_to=Driver_app.models.truncate_filename)),
                ('vehicle_Photo', models.ImageField(max_length=250, upload_to=Driver_app.models.truncate_filename)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
