# Generated by Django 4.2.6 on 2024-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_alter_customuser_is_active_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(max_length=250, upload_to='img/profile'),
        ),
    ]
