# Generated by Django 5.0.7 on 2024-07-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0006_otpstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpstorage',
            name='otp',
            field=models.CharField(max_length=10),
        ),
    ]
