name: Deploy Django Application to Production

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/Caboo_backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Backend/Caboo_backend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/caboo-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/caboo-backend:${{ github.sha }}

    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_PEM_KEY }}
        script: |
          echo "Starting deployment process..."
          
          # Navigate to the project directory
          cd /path/to/your/Caboo-cab/Backend/Caboo_backend
          
          echo "Stopping existing containers..."
          docker-compose down
          
          echo "Pulling latest images..."
          docker-compose pull
          
          echo "Starting containers..."
          docker-compose up -d
          
          echo "Running migrations..."
          docker-compose exec -T web python manage.py migrate
          
          echo "Collecting static files..."
          docker-compose exec -T web python manage.py collectstatic --noinput
          
          echo "Deployment completed!"
          
          echo "Checking container status..."
          docker-compose ps