name: Deploy Django Application

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/Caboo_backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Setup Docker Buildx for multi-platform builds (if needed)
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Step 4: Build the Docker image and push it to Docker Hub
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/caboo-backend:latest.
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/caboo-backend:latest


    # Step 5: Setup SSH to access AWS EC2
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SERVER_PEM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    # Step 6: Deploy to AWS EC2
    - name: Deploy on AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
          # Log in to Docker Hub on the EC2 instance
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          # Pull the latest Docker image from Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/caboo-backend:${{ github.sha }}

          # Stop the running container if it exists
          docker stop caboo_backend || true

          # Remove the container if it exists
          docker rm caboo_backend || true

          # Run the container with the latest image
          docker run -d --name caboo_backend -p 8001:8001 ${{ secrets.DOCKERHUB_USERNAME }}/caboo-backend:latest

          # Optional: Tail logs for debugging (you can remove this if not needed)
          docker logs -f caboo_backend
        EOF
