name: Deploy Django Application

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/Caboo_backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Backend/Caboo_backend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/caboo-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/caboo-backend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
    - name: Pull Docker image from Docker Hub
      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/caboo-backend:latest

    - name: Delete old container
      run: sudo docker rm -f caboo-backend-container || true  # Avoid error if container doesn't exist

    - name: Run new Docker container
      run: |
        sudo docker run -d -p 8000:8000 --name caboo-backend-container \
        --env-file ./Backend/Caboo_backend/.env \
        ${{ secrets.DOCKERHUB_USERNAME }}/caboo-backend:latest

    - name: Verify container is running
      run: sudo docker ps -a
