name: Deploy on AWS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      run : |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/Caboo_backend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/Caboo_backend:latest

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SERVER_PEM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy on AWS EC2 
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/Caboo_backend:latest
          docker stop Caboo_backend || true
          docker rm Caboo_backend || true
          docker run -d --name Caboo_backend -p 8001:8001 ${{ secrets.DOCKERHUB_USERNAME }}/Caboo_backend:latest
        EOF