name: Deploy Django Application

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/Caboo_backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Backend/Caboo_backend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/Caboo_backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/Caboo_backend:${{ github.sha }}

    - name: Run tests
      run: |
        cd Backend/Caboo_backend
        docker-compose run web python manage.py test

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_PEM_KEY }}
        script: |
          cd /path/to/your/project
          git pull origin main
          docker-compose pull
          docker-compose up -d
          docker system prune -af